[package]
name = "pubchat"
edition = "2024"
description = "pubchat extension"

[lib]
name = "pubchat"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
log = {workspace = true}
thiserror = { workspace = true }